### ISSUE TITLE
some funcall ... mode problems

### ISSUE THREAD

**Issue by holtzermann17** [zk-phi/togetherly#4]
Hi, I'm very excited about togetherly which I am using with a friend of mine.  Here is one small problem we've noticed.  The appropriate "fix" might be org mode configuration, but I think I have a work around in togetherly.el, so I will comment here about it.

On [L454](https://github.com/zk-phi/togetherly/blob/master/togetherly.el#L454) there's the following s-exp:

```lisp
(funcall (or (and (fboundp mode) mode) 'fundamental-mode))
```

In an org mode file, with default configurations, restarting the mode causes all of the blocks to fold.  It can be annoying for this to happen at random times when editing the buffer.  So my work around was just to comment out the line above.  Another fix would be to add `show-all` to the local org mode hook, similar to this question on Stack Exchange: https://emacs.stackexchange.com/questions/21335/prevent-folding-org-files-opened-by-ediff/21336

However, perhaps there is a more sophisticated approach to sharing the mode, i.e., rewriting L454 so that it doesn't turn the mode back on if the mode sent by the server is already equal to the local major mode.  That can be detected.

```lisp
  (with-current-buffer buffer-or-string
     major-mode)
```

**Comment by zk-phi** [comment]
Thanks for reporting!

Fixed with this approach :

> doesn't turn the mode back on if the mode sent by the server is already equal to the local major mode
